### DISCUSSION TITLE
Business DIY 4 chargers

### DISCUSSION THREAD

**Discussion by HA-TB303** [dingo35/SmartEVSE-3.5#36] [Show and tell]
Great stuff this smart EVSE:

![CleanShot 2024-03-20 at 15 32 13](https://github.com/dingo35/SmartEVSE-3.5/assets/9609805/f45df486-d3ed-40d7-afdc-deec28e458ea)

![CleanShot 2024-03-20 at 15 33 01](https://github.com/dingo35/SmartEVSE-3.5/assets/9609805/199950f0-756a-41dd-8c2b-4e603f7fdb30)

![CleanShot 2024-03-20 at 15 34 47](https://github.com/dingo35/SmartEVSE-3.5/assets/9609805/f61a35b2-59b3-4ebb-8f1d-a41925fd07bd)

**Comment by dingo35** [comment]
Very nice!

**Comment by mstegen** [comment]
Nice!

**Comment by TommyboyNL** [comment]
Looking good! Are you willing to share the YAML for your HA dashboard?

**Comment by HA-TB303** [comment]
Sure. I use the MQTT entities.

```
type: vertical-stack
title: Lader 1 (SmartEVSE-6845)
cards:
  - type: horizontal-stack
    cards:
      - color: auto
        entity: sensor.smartevse_6845_state
        name: '[[[ return states["sensor.smartevse_6845_state"].state ]]]'
        state:
          - color: Grey
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6845_state'].state === 'Ready
              to Charge' ]]]
          - color: blue
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6845_state'].state ===
              'Charging' ]]]
          - color: orange
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6845_state'].state ===
              'Connected to EV' ]]]
          - icon: mdi:ev-plug-type2
            operator: default
        styles:
          card:
            - height: 160px
        tap_action:
          action: more-info
        type: custom:button-card
        theme: Mushroom
      - type: gauge
        entity: sensor.smartevse_6845_evchargepower
        name: ' '
        min: 0
        max: 7
        severity:
          green: 0
          yellow: 3.5
          red: 7
  - type: horizontal-stack
    cards:
      - type: gauge
        entity: sensor.smartevse_6845_evcurrentl1
        name: L1
        unit: A
        min: 0
        max: 10
      - type: gauge
        entity: sensor.smartevse_6845_evcurrentl2
        name: L2
        unit: A
        min: 0
        max: 10
      - type: gauge
        entity: sensor.smartevse_6845_evcurrentl3
        name: L3
        unit: A
        min: 0
        max: 10
  - type: entities
    entities:
      - entity: select.smartevse_6845_mode
        name: Modus
      - entity: number.smartevse_6845_chargecurrentoverride
        name: Laadlimiet (A)
      - entity: sensor.smartevse_6845_evenergycharged
        name: Geladen laatste sessie
      - entity: sensor.smartevse_6845_evtotalenergycharged
        name: Totaal geladen
      - entity: sensor.smartevse_6845_error
        name: Error
      - entity: sensor.smartevse_6845_esptemp
        name: ESP Temp
      - entity: sensor.smartevse_6845_espuptime
        name: ESP Uptime
      - entity: sensor.smartevse_6845_wifibssid
        name: WiFi BSSID
      - entity: sensor.smartevse_6845_wifirssi
        name: WiFi RSSI
      - entity: sensor.smartevse_6845_wifissid
        name: WiFi SSID
    state_color: false
    show_header_toggle: false
```

Which results in:

![CleanShot 2024-03-21 at 11 18 43](https://github.com/dingo35/SmartEVSE-3.5/assets/9609805/09a8f668-2e36-4692-95f9-233f24bcfa14)

**Reply by TommyboyNL** [reply]
I'm still fighting with the layout, but I made some changes based on your YAMLs:
![2024-03-25 22_32_06-Lader – Home Assistant — Mozilla Firefox](https://github.com/dingo35/SmartEVSE-3.5/assets/20584405/4264fc09-838b-46ac-894a-a8448a917e44)
I want the connector to be 66% of the width, but if I configure the width in pixels it looks good on my PC but not on my phone... It also needs to be the same height as the two buttons next to it together...

My charger is located right besides a public road (dead end, so not very busy) and I don't like fussing with RFID cards, so I use HA and the two buttons to turn the charger on and off.
```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - color: auto
        entity: sensor.smartevse_5988_state
        name: '[[[ return states["sensor.smartevse_5988_state"].state ]]]'
        state:
          - color: Grey
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_5988_state'].state === 'Ready
              to Charge' ]]]
          - color: rgb(28, 128, 199)
            icon: mdi:ev-plug-type2
            name: >-
              [[[ return states["sensor.smartevse_5988_evchargepower"].state +" W"]]]
            operator: template
            value: >
              [[[ return states['sensor.smartevse_5988_state'].state ===
              'Charging' ]]]
          - color: rgb(255,152,0)
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_5988_state'].state ===
              'Connected to EV' ]]]
          - icon: mdi:ev-plug-type2
            operator: default
        styles:
          card:
             - height: 160px
        tap_action:
          action: more-info
        type: custom:button-card
        theme: Mushroom
      - type: vertical-stack
        cards:
          - type: button
            icon: mdi:battery-charging
            tap_action:
              action: call-service
              service: select.select_option
              target:
                entity_id: select.smartevse_5988_mode
              data:
                option: "Smart"
          - type: button
            icon: mdi:battery-off
            tap_action:
              action: call-service
              service: select.select_option
              target:
                entity_id: select.smartevse_5988_mode
              data:
                option: "Off"
  - type: horizontal-stack
    cards:
      - type: gauge
        entity: sensor.smartevse_5988_evcurrentl1
        name: L1
        unit: A
        min: 0
        max: 16
      - type: gauge
        entity: sensor.smartevse_5988_evcurrentl2
        name: L2
        unit: A
        min: 0
        max: 16
      - type: gauge
        entity: sensor.smartevse_5988_evcurrentl3
        name: L3
        unit: A
        min: 0
        max: 16
  - type: entities
    entities:
      - entity: select.smartevse_5988_mode
        name: Modus
      - entity: number.smartevse_5988_chargecurrentoverride
        name: Laadlimiet (A)
      - entity: sensor.smartevse_5988_evenergycharged
        name: Geladen laatste sessie
      - entity: sensor.smartevse_5988_evtotalenergycharged
        name: Totaal geladen
      - entity: sensor.smartevse_5988_error
        name: Error
      - entity: sensor.smartevse_5988_esptemp
        name: ESP Temp
      - entity: sensor.smartevse_5988_espuptime
        name: ESP Uptime
    state_color: false
    show_header_toggle: false
```

**Reply by HA-TB303** [reply]
You could solve that pretty easily by creating ONE button for charge/stop and change the icon and color accordingly. That's pretty well documented in the custom button docs.

**Comment by HA-TB303** [comment]
You do need the custom button card (HACS)
https://github.com/custom-cards/button-card

Please share any improvements you make ;)

**Reply by TommyboyNL** [reply]
Thanks for sharing, and will do!

**Reply by HA-TB303** [reply]
Small addition: Charging tiles for the 4 chargers that will show the state and in case of charging show to actual Kw.

![CleanShot 2024-03-25 at 11 39 02](https://github.com/dingo35/SmartEVSE-3.5/assets/9609805/31fb241f-3a42-4155-a18f-3176090aa4b4)

```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - color: auto
        entity: sensor.smartevse_6845_state
        name: '[[[ return "1 - "+states["sensor.smartevse_6845_state"].state ]]]'
        state:
          - color: Grey
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6845_state'].state === 'Ready
              to Charge' ]]]
          - color: rgb(28, 128, 199)
            icon: mdi:ev-plug-type2
            name: >-
              [[[ return "1 -
              "+states["sensor.smartevse_6845_evchargepower"].state +" Kw"]]]
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6845_state'].state ===
              'Charging' ]]]
          - color: rgb(255,152,0)
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6845_state'].state ===
              'Connected to EV' ]]]
          - icon: mdi:ev-plug-type2
            operator: default
        styles:
          card:
            - height: 120px
        tap_action:
          action: more-info
        type: custom:button-card
        theme: Mushroom
      - color: auto
        entity: sensor.smartevse_6847_state
        name: '[[[ return "2 - "+states["sensor.smartevse_6847_state"].state ]]]'
        state:
          - color: Grey
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6847_state'].state === 'Ready
              to Charge' ]]]
          - color: rgb(28, 128, 199)
            icon: mdi:ev-plug-type2
            name: >-
              [[[ return "2 -
              "+states["sensor.smartevse_6847_evchargepower"].state +" Kw"]]]
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6847_state'].state ===
              'Charging' ]]]
          - color: rgb(255,152,0)
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6847_state'].state ===
              'Connected to EV' ]]]
          - icon: mdi:ev-plug-type2
            operator: default
        styles:
          card:
            - height: 120px
        tap_action:
          action: more-info
        type: custom:button-card
        theme: Mushroom
  - type: horizontal-stack
    cards:
      - color: auto
        entity: sensor.smartevse_6848_state
        name: '[[[ return "3 - "+states["sensor.smartevse_6848_state"].state ]]]'
        state:
          - color: Grey
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6848_state'].state === 'Ready
              to Charge' ]]]
          - color: rgb(28, 128, 199)
            icon: mdi:ev-plug-type2
            name: >-
              [[[ return "3 -
              "+states["sensor.smartevse_6848_evchargepower"].state +" Kw"]]]
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6848_state'].state ===
              'Charging' ]]]
          - color: rgb(255,152,0)
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6848_state'].state ===
              'Connected to EV' ]]]
          - icon: mdi:ev-plug-type2
            operator: default
        styles:
          card:
            - height: 120px
        tap_action:
          action: more-info
        type: custom:button-card
        theme: Mushroom
      - color: auto
        entity: sensor.smartevse_6849_state
        name: '[[[ return "4 - "+states["sensor.smartevse_6849_state"].state ]]]'
        state:
          - color: Grey
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6849_state'].state === 'Ready
              to Charge' ]]]
          - color: rgb(28, 128, 199)
            icon: mdi:ev-plug-type2
            name: >-
              [[[ return "4 -
              "+states["sensor.smartevse_6849_evchargepower"].state +" Kw"]]]
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6849_state'].state ===
              'Charging' ]]]
          - color: rgb(255,152,0)
            icon: mdi:ev-plug-type2
            operator: template
            value: >
              [[[ return states['sensor.smartevse_6849_state'].state ===
              'Connected to EV' ]]]
          - icon: mdi:ev-plug-type2
            operator: default
        styles:
          card:
            - height: 120px
        tap_action:
          action: more-info
        type: custom:button-card
        theme: Mushroom
```
